debug: true
server:
  port: 9999

security:
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /dashboard/login
management:
  security:
    role: ADMIN

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://sso.procesa.com:8080/openam/oauth2/access_token
      userAuthorizationUri: http://sso.procesa.com:8080/openam/oauth2/authorize
      clientId: procesa
      clientSecret: 123456
      scope: All
    resource:
      userInfoUri: http://sso.procesa.com:8080/openam/oauth2/tokeninfo